/****** Object:  Database [Porteria]    Script Date: 15/5/2024 17:24:01 ******/
CREATE DATABASE [Porteria]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;
GO
ALTER DATABASE [Porteria] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Porteria] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Porteria] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Porteria] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Porteria] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Porteria] SET ARITHABORT OFF 
GO
ALTER DATABASE [Porteria] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Porteria] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Porteria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Porteria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Porteria] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Porteria] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Porteria] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Porteria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Porteria] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [Porteria] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Porteria] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Porteria] SET  MULTI_USER 
GO
ALTER DATABASE [Porteria] SET ENCRYPTION ON
GO
ALTER DATABASE [Porteria] SET QUERY_STORE = ON
GO
ALTER DATABASE [Porteria] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO
/****** Object:  Table [dbo].[Empresa]    Script Date: 15/5/2024 17:24:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empresa](
	[IdEmpresa] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NULL,
 CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED 
(
	[IdEmpresa] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ingreso]    Script Date: 15/5/2024 17:24:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingreso](
	[IdIngreso] [int] IDENTITY(1,1) NOT NULL,
	[FechaIngreso] [datetime] NOT NULL,
	[FechaEgreso] [datetime] NULL,
	[IdEmpresa] [int] NOT NULL,
	[IdVehiculo] [int] NOT NULL,
	[IdPersona] [int] NOT NULL,
	[IdTipoCarga] [int] NOT NULL,
	[Peso] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Ingreso] PRIMARY KEY CLUSTERED 
(
	[IdIngreso] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persona]    Script Date: 15/5/2024 17:24:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persona](
	[IdPersona] [int] IDENTITY(1,1) NOT NULL,
	[TipoDocumento] [nvarchar](3) NOT NULL,
	[Documento] [nvarchar](20) NOT NULL,
	[Pais] [nvarchar](2) NOT NULL,
	[Celular] [nvarchar](20) NULL,
	[Nombres] [nvarchar](100) NOT NULL,
	[Apellidos] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED 
(
	[IdPersona] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoCarga]    Script Date: 15/5/2024 17:24:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoCarga](
	[IdTipoCarga] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TipoCarga] PRIMARY KEY CLUSTERED 
(
	[IdTipoCarga] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vehiculo]    Script Date: 15/5/2024 17:24:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehiculo](
	[IdVehiculo] [int] IDENTITY(1,1) NOT NULL,
	[Matricula] [nvarchar](20) NOT NULL,
	[Pais] [nvarchar](2) NOT NULL,
 CONSTRAINT [PK_Vehiculo] PRIMARY KEY CLUSTERED 
(
	[IdVehiculo] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ingreso]  WITH CHECK ADD  CONSTRAINT [FK_Ingreso_Empresa] FOREIGN KEY([IdEmpresa])
REFERENCES [dbo].[Empresa] ([IdEmpresa])
GO
ALTER TABLE [dbo].[Ingreso] CHECK CONSTRAINT [FK_Ingreso_Empresa]
GO
ALTER TABLE [dbo].[Ingreso]  WITH CHECK ADD  CONSTRAINT [FK_Ingreso_Persona] FOREIGN KEY([IdPersona])
REFERENCES [dbo].[Persona] ([IdPersona])
GO
ALTER TABLE [dbo].[Ingreso] CHECK CONSTRAINT [FK_Ingreso_Persona]
GO
ALTER TABLE [dbo].[Ingreso]  WITH CHECK ADD  CONSTRAINT [FK_Ingreso_TipoCarga] FOREIGN KEY([IdTipoCarga])
REFERENCES [dbo].[TipoCarga] ([IdTipoCarga])
GO
ALTER TABLE [dbo].[Ingreso] CHECK CONSTRAINT [FK_Ingreso_TipoCarga]
GO
ALTER TABLE [dbo].[Ingreso]  WITH CHECK ADD  CONSTRAINT [FK_Ingreso_Vehiculo] FOREIGN KEY([IdVehiculo])
REFERENCES [dbo].[Vehiculo] ([IdVehiculo])
GO
ALTER TABLE [dbo].[Ingreso] CHECK CONSTRAINT [FK_Ingreso_Vehiculo]
GO
ALTER DATABASE [Porteria] SET  READ_WRITE 
GO
